language: ruby
sudo: false
rvm:
  - 2.2.6
script:
  - bundle
  - rake test
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
after_success:
  - curl https://darmstadt.freifunk.net/deploy
